resolver: lts-12.0

packages:
- coinmetrics
- coinmetrics-all-blockchains
- coinmetrics-bitcoin
- coinmetrics-bytecoin
- coinmetrics-cardano
- coinmetrics-eos
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-monitor
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar
- coinmetrics-tron
- coinmetrics-waves

extra-deps:
- diskhash-0.0.4.0
- prometheus-client-1.0.0
- git: https://github.com/quyse/hanalytics.git
  commit: b24c3baecab6fa733ff07d1799ff64013ecbe64c
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres
